<?php
return [
    'database' => [
        'dictionary_row_limit' => 1000,
        'cache_row_limit' => 5000,
    ],
    'cache' => [
        'ttl' => 3600,
        'prefix' => 'poetrax_',
        'warmup_ttl' => 86400,
    ],
    'pagination' => [
        'default_page' => 1,
        'default_limit' => 20,
        'max_limit' => 100,
    ],
	'track' => [
    'fields' => [
        'is_approved' => 'is_approved',
        'is_active' => 'is_active',
        'created_at' => 'created_at',
    ],
    'recent_limit' => 10,
	],
	'donate' => [                     
        'min' => 100,
        'max' => 10000,
    ],
	   'tables' => [
        'track' => 'bm_ctbl000_track',
        'poet' => 'bm_ctbl000_poet',
        'poem' => 'bm_ctbl000_poem',
        'interaction' => 'bm_ctbl000_interaction',
        'user' => 'bm_ctbl000_user',
        'payment' => 'bm_ctbl000_payment',
        'acception' => 'bm_ctbl000_acception',
        'price_list' => 'bm_ctbl000_price_list',
        'mood' => 'bm_ctbl000_mood',
        'theme' => 'bm_ctbl000_theme',
        'music_genre' => 'bm_ctbl000_music_genre',
        'music_style' => 'bm_ctbl000_music_style',
        'music_instrument' => 'bm_ctbl000_music_instrument',
        'voice_gender' => 'bm_ctbl000_music_voice_gender',
        'voice_character' => 'bm_ctbl000_voice_character',
        'voice_register' => 'bm_ctbl000_voice_register',
        'track_music_detail' => 'bm_ctbl000_track_music_detail',
        'track_self_text' => 'bm_ctbl000_track_self_text',
        'user_balance' => 'bm_ctbl000_user_balance',
        'user_session' => 'bm_ctbl000_user_session',
        'comment' => 'bm_ctbl000_comment',
        'docs' => 'bm_ctbl000_docs',
        'img' => 'bm_ctbl000_img',
        'img_theme' => 'bm_ctbl000_img_theme',
        'language' => 'bm_ctbl000_language',
        'music_direction' => 'bm_ctbl000_music_direction',
        'music_presentation' => 'bm_ctbl000_music_presentation',
        'music_suno_style' => 'bm_ctbl000_music_suno_style',
        'music_temp' => 'bm_ctbl000_music_temp',
        'music_voice_group' => 'bm_ctbl000_music_voice_group',
        'poet_centuries' => 'bm_ctbl000_poet_centuries',
        'poet_movements' => 'bm_ctbl000_poet_movements',
        'properties_cache' => 'bm_ctbl000_properties_cache',
        'referral' => 'bm_ctbl000_referral',
        'subscription' => 'bm_ctbl000_subscription',
        'suno_user_keys' => 'bm_ctbl000_suno_user_keys',
        'track_review' => 'bm_ctbl000_track_review',
        'track_version' => 'bm_ctbl000_track_version',
        'user_account' => 'bm_ctbl000_user_account',
        'user_inventory' => 'bm_ctbl000_user_inventory',
        'user_streak' => 'bm_ctbl000_user_streak',
        'yookassa_payment' => 'bm_ctbl000_yookassa_payment',
		'block' => 'bm_ctbl000_block',
		'service' => 'bm_ctbl000_service',
		'user_service_access' => 'bm_ctbl000_user_service_access',
		'message' => 'bm_ctbl000_message',
		'product_category' => 'bm_ctbl000_product_category',
		'product' => 'bm_ctbl000_product',
		'product_variant' => 'bm_ctbl000_product_variant',
		'product_image' => 'bm_ctbl000_product_image',
		'cart' => 'bm_ctbl000_cart',
		'cart_item' => 'bm_ctbl000_cart_item',
		'order' => 'bm_ctbl000_order',
		'order_item' => 'bm_ctbl000_order_item',
		'admin' => 'bm_ctbl000_admin',
		'admin_log' => 'bm_ctbl000_admin_log',
		'report' => 'bm_ctbl000_report',
    ],
];